GET http://localhost:3001/api/article/recent
Content-Type: application/json
Authorization: Basic eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVlYmU3NjNiNTNiODFkMzVkZjVjMWQyMyIsImVtYWlsIjoibmJyZXNrYW51NzNAZ21haWwuY29tIiwiZXhwIjoxNTk0ODIwNjU2LCJpYXQiOjE1ODk2MzY2NTZ9.YnvHGO2-axd9bW6WfcA1xpmmiISf0UcK7PcU7Yvp4IA
